# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-15 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='area',
            new_name='region',
        ),
    ]
