# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-15 14:36
from __future__ import unicode_literals

import consumer.models.property
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_auto_20190315_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
        migrations.AddField(
            model_name='photo',
            name='content',
            field=models.ImageField(default='', upload_to=consumer.models.property.photo_upload_filename, verbose_name='Image file'),
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
    ]
